#!/bin/bash
#PBS -N Make_Pileup
#PBS -S /bin/bash
#PBS -l walltime=12:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=2gb
#PBS -o $HOME/LOGS/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -e $HOME/LOGS/${PBS_JOBNAME}.o${PBS_JOBID}
#PBS -t 1-25

module load samtools/1.2
genome=/group/referenceFiles/Homo_sapiens/NCBI/b37.GATKbundle/v2.8/human_g1k_v37.fasta

cd /scratch/anath1
samtools mpileup -f $genome Dedup_RH1.REF_${PBS_ARRAYID}.bam > Dedup_RH1.REF_${PBS_ARRAYID}.pileup
samtools mpileup -f $genome Dedup_RH5.REF_${PBS_ARRAYID}.bam > Dedup_RH5.REF_${PBS_ARRAYID}.pileup
