#!/bin/bash
#PBS -N VARSCAN_SNP
#PBS -S /bin/bash
#PBS -l walltime=48:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=8gb
#PBS -o $HOME/LOGS/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -e $HOME/LOGS/${PBS_JOBNAME}.o${PBS_JOBID}
#PBS t 1-25
 
module load java/jdk1.8.0_45
cd /scratch/anath1

java -jar /apps/software/varscan2/2.3.7/VarScan.v2.3.7.jar somatic \
Dedup_RH1.REF_${PBS_ARRAYID}.pileup \
Dedup_RH5.REF_${PBS_ARRAYID}.pileup \
P1_varscan_${PBS_ARRAYID}
